# Generated by Django 5.1.9 on 2026-06-07 09:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fileaccesslog",
            new_name="file_manage_file_id_79245a_idx",
            old_name="file_manager_file_log_idx",
        ),
        migrations.RenameIndex(
            model_name="fileaccesslog",
            new_name="file_manage_accesse_9becac_idx",
            old_name="file_manager_user_log_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadedfile",
            new_name="file_manage_uploade_2e70dc_idx",
            old_name="file_manager_upload_user_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadedfile",
            new_name="file_manage_categor_29868e_idx",
            old_name="file_manager_cat_public_idx",
        ),
        migrations.AddField(
            model_name="fileaccesslog",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileaccesslog",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="fileaccesslog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="fileaccesslog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
