# Generated by Django 5.1.9 on 2026-06-07 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("platform", models.CharField(db_index=True, max_length=20)),
                ("current_version", models.CharField(max_length=40)),
                ("minimum_supported_version", models.CharField(max_length=40)),
                ("force_update", models.BooleanField(default=False)),
                ("release_notes", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "current_version"],
                        name="splash_appr_platfor_4c7fa5_idx",
                    )
                ],
            },
        ),
    ]
