# Generated by Django 5.1.9 on 2026-05-10 16:23

import apps.ocr_processing.utils.file_naming
import common.validators.files
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRProcessingRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.ocr_processing.utils.file_naming.ocr_image_upload_path,
                        validators=[common.validators.files.validate_image_upload],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=9),
                ),
                ("address", models.TextField(blank=True)),
                ("extracted_text", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["processing_status", "created_at"],
                        name="ocr_process_process_3d15ad_idx",
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="ocr_process_latitud_726015_idx",
                    ),
                ],
            },
        ),
    ]
