# Generated by Django 5.1.9 on 2026-05-10 16:24

import apps.ocr_processing.utils.file_naming
import apps.ocr_processing.validators.image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrprocessingrecord",
            name="image",
            field=models.ImageField(
                upload_to=apps.ocr_processing.utils.file_naming.ocr_image_upload_path,
                validators=[
                    apps.ocr_processing.validators.image.validate_ocr_image_upload
                ],
            ),
        ),
    ]
